name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: configurar Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Instalar dependecias
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Correr test
      run: |
        python -m unittest discover -s . -p 'test_*.py'
